// Code generated by Slice Machine. DO NOT EDIT.

import ImageOnly from './ImageOnly';
import TextAndImage from './TextAndImage';
import TextOnly from './TextOnly';

export {
	ImageOnly,
	TextAndImage,
	TextOnly,
};

export const components = {
	image_only: ImageOnly,
	text_and_image: TextAndImage,
	text_only: TextOnly,
};
