// Code generated by Slice Machine. DO NOT EDIT.

import TextAndImage from './TextAndImage';
import TextOnly from './TextOnly';

export {
	TextAndImage,
	TextOnly,
};

export const components = {
	text_and_image: TextAndImage,
	text_only: TextOnly,
};
