// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
    text_and_image: dynamic(() => import('./TextAndImage')),
    text_only: dynamic(() => import('./TextOnly')),
}
