import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
	return (
		<Html>
			<Head>
				<link rel="icon" href="/images/logo.svg" />
				<meta name="description" content="Generated by create next app" />
			</Head>
			<body>
				<Main />
				<NextScript />
			</body>
		</Html>
	)
}
